<script>
  /*
用 promise 实现以下功能。
具体： fn1和fn2都是异步函数，f1、fn2同时执行，并且fn1、fn2的结果是 fn3的参数。当fn1或者fn2发生错误时，fn3照常执行，此时的参数为空。
*/
  eg:
  function sendRquest1(t) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve(t)
      }, t)
    })
  }

  let fn1 = async () => {

    // 发送请求
    const data = await sendRquest1(1000);
    return data;
  }
  let fn2 = async () => {

    // 发送请求
    const data = await sendRquest2(2000);
    return data;
  }
  let fn3 = (...args) => {
    console.log(args);
  }
  Promise.all([fn1(), fn2()])   // .all 一个失败就失败
  Promise.allSettled([fn1(), fn2()]).then(fn3)  // .allSettled  不管成功失败全都输出
  // Promise.any([fn1(), fn2()]).then(fn3)


  // Promise.All的实现
  Promise.myall = function (promiseArr) {
    return new Promise((resolve, reject) => {
      let res = [], count = 0, len = promiseArr.length
      for (let i = 0; i < len; i++) {
        // i 原来在数组里面的循序
        promiseArr[i].then((r) => {
          // 最终成功的时候的循序
          res[i] = r
          count++
          console.log(count);
          if (count === len) {
            resolve(res)
          }
        })
          .catch(() => {
            c++
            res[i] = null
            if (count === len) {
              resolve(res)
            }
          })
      }
    })
  }
</script>